// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyOnlineShop.Inventory.Infrastructure.Persistence;

#nullable disable

namespace MyOnlineShop.Inventory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20261005073919_InitialInventory")]
    partial class InitialInventory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyOnlineShop.Inventory.Domain.InventoryMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("QuantityAfter")
                        .HasColumnType("bigint");

                    b.Property<long>("QuantityBefore")
                        .HasColumnType("bigint");

                    b.Property<long>("QuantityDelta")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<Guid>("StockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OperationId")
                        .IsUnique();

                    b.HasIndex("Reference");

                    b.HasIndex("StockId", "CreatedAtUtc");

                    b.HasIndex("Type", "CreatedAtUtc");

                    b.ToTable("Movements", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_Movements_Quantity", "[QuantityDelta] <> 0 AND [QuantityBefore] >= 0 AND [QuantityAfter] >= 0 AND [QuantityAfter] <= 1000000000000 AND [QuantityAfter] = [QuantityBefore] + [QuantityDelta]");

                            t.HasCheckConstraint("CK_Movements_Type", "([Type] IN (1, 3) AND [QuantityDelta] > 0) OR ([Type] IN (2, 4) AND [QuantityDelta] < 0) OR [Type] = 5");
                        });
                });

            modelBuilder.Entity("MyOnlineShop.Inventory.Domain.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("LowStockThreshold")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("WarehouseId", "ProductVariantId")
                        .IsUnique();

                    b.ToTable("Stocks", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_Stocks_Quantity", "[Quantity] >= 0 AND [Quantity] <= 1000000000000");

                            t.HasCheckConstraint("CK_Stocks_Threshold", "[LowStockThreshold] >= 0 AND [LowStockThreshold] <= 1000000000000");
                        });
                });

            modelBuilder.Entity("MyOnlineShop.Inventory.Domain.StockAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovementId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MovementId")
                        .IsUnique();

                    b.ToTable("Adjustments", "inventory");
                });

            modelBuilder.Entity("MyOnlineShop.Inventory.Domain.StockReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovementId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MovementId")
                        .IsUnique();

                    b.ToTable("Receipts", "inventory");
                });

            modelBuilder.Entity("MyOnlineShop.Inventory.Domain.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Warehouses", "inventory");
                });

            modelBuilder.Entity("MyOnlineShop.Inventory.Domain.InventoryMovement", b =>
                {
                    b.HasOne("MyOnlineShop.Inventory.Domain.Stock", null)
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MyOnlineShop.Inventory.Domain.Stock", b =>
                {
                    b.HasOne("MyOnlineShop.Inventory.Domain.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MyOnlineShop.Inventory.Domain.StockAdjustment", b =>
                {
                    b.HasOne("MyOnlineShop.Inventory.Domain.InventoryMovement", null)
                        .WithOne()
                        .HasForeignKey("MyOnlineShop.Inventory.Domain.StockAdjustment", "MovementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MyOnlineShop.Inventory.Domain.StockReceipt", b =>
                {
                    b.HasOne("MyOnlineShop.Inventory.Domain.InventoryMovement", null)
                        .WithOne()
                        .HasForeignKey("MyOnlineShop.Inventory.Domain.StockReceipt", "MovementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
