<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
    <!-- Compatible security fix for the OpenAPI dependency. -->
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <ProjectReference Include="../src/BuildingBlocks/Infrastructure/MyOnlineShop.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="../src/Modules/Identity/Presentation/MyOnlineShop.Identity.Presentation.csproj" />
    <ProjectReference Include="../src/Modules/Catalog/Presentation/MyOnlineShop.Catalog.Presentation.csproj" />
    <ProjectReference Include="../src/Modules/Inventory/Presentation/MyOnlineShop.Inventory.Presentation.csproj" />
    <ProjectReference Include="../src/Modules/Cart/Presentation/MyOnlineShop.Cart.Presentation.csproj" />
    <ProjectReference Include="../src/Modules/Pricing/Presentation/MyOnlineShop.Pricing.Presentation.csproj" />
    <ProjectReference Include="../src/Modules/Discount/Presentation/MyOnlineShop.Discount.Presentation.csproj" />
    <ProjectReference Include="../src/Modules/Order/Presentation/MyOnlineShop.Order.Presentation.csproj" />
    <ProjectReference Include="../src/Modules/Wallet/Presentation/MyOnlineShop.Wallet.Presentation.csproj" />
  </ItemGroup>

</Project>
